module Corpus where

data Nat = Zero | Succ Nat

idB b = b
notB b = case b of { True -> False; False -> True }
constTrue b = True
constFalse b = False
andB a b = case a of { True -> b; False -> False }
orB a b = case a of { True -> True; False -> b }
nandB a b = notB (andB a b)
norB a b = notB (orB a b)
xorB a b = case a of { True -> notB b; False -> b }
implyB a b = case a of { True -> b; False -> True }
nimplyB a b = andB a (notB b)
eqB a b = case a of { True -> b; False -> notB b }
and3 a b c = andB a (andB b c)
or3 a b c = orB a (orB b c)
xor3 a b c = xorB a (xorB b c)
majority3 a b c = orB (andB a b) (orB (andB a c) (andB b c))
inc n = Succ n
plus2 n = Succ (Succ n)
plus3 n = Succ (Succ (Succ n))
plus4 n = Succ (Succ (Succ (Succ n)))
plus5 n = Succ (Succ (Succ (Succ (Succ n))))
plus6 n = Succ (Succ (Succ (Succ (Succ (Succ n)))))
plus7 n = Succ (Succ (Succ (Succ (Succ (Succ (Succ n))))))
plus8 n = Succ (Succ (Succ (Succ (Succ (Succ (Succ (Succ n)))))))
idn n = n
czero n = Zero
predn n = case n of { Zero -> Zero; Succ m -> m }
add a b = case a of { Zero -> b; Succ m -> Succ (add m b) }
mul a b = case a of { Zero -> Zero; Succ m -> add b (mul m b) }
double n = add n n
triple n = add n (add n n)
quad n = double (double n)
addThree a b c = add a (add b c)
addFour a b c d = add (add a b) (add c d)
square n = mul n n
cube n = mul n (mul n n)
sextuple n = add (triple n) (triple n)
mulThree a b c = mul a (mul b c)
addMul a b = add a (mul a b)
sumSquares a b = add (square a) (square b)
doubleInc n = Succ (double n)
quadInc n = Succ (quad n)
isZero n = case n of { Zero -> True; Succ m -> False }
notZero n = notB (isZero n)
isOne n = case n of { Zero -> False; Succ m -> isZero m }
isTwo n = case n of { Zero -> False; Succ m -> isOne m }
leq a b = case a of { Zero -> True; Succ m -> case b of { Zero -> False; Succ n -> leq m n } }
eqNat a b = andB (leq a b) (leq b a)
maxNat a b = case leq a b of { True -> b; False -> a }
minNat a b = case leq a b of { True -> a; False -> b }
subNat a b = case b of { Zero -> a; Succ n -> case a of { Zero -> Zero; Succ m -> subNat m n } }
evenNat n = case n of { Zero -> True; Succ m -> case m of { Zero -> False; Succ n' -> evenNat n' } }
oddNat n = notB (evenNat n)
facNat n = case n of { Zero -> Succ Zero; Succ m -> mul (Succ m) (facNat m) }
powNat a b = case b of { Zero -> Succ Zero; Succ n -> mul a (powNat a n) }
fibNat n = case n of { Zero -> Succ Zero; Succ m -> case m of { Zero -> Succ Zero; Succ n' -> add (fibNat m) (fibNat n') } }
boolToNat b = case b of { True -> Succ Zero; False -> Zero }
isThree n = case n of { Zero -> False; Succ m -> isTwo m }
isFour n = case n of { Zero -> False; Succ m -> isThree m }
lt a b = andB (leq a b) (notB (eqNat a b))
gt a b = lt b a
geq a b = notB (lt a b)
half n = case n of { Zero -> Zero; Succ m -> case m of { Zero -> Zero; Succ n' -> Succ (half n') } }
sumToN n = case n of { Zero -> Zero; Succ m -> add n (sumToN m) }
ack m n = case m of { Zero -> inc n; Succ m' -> case n of { Zero -> ack m' (inc Zero); Succ n' -> ack m' (ack m n') } }
max3 a b c = maxNat a (maxNat b c)
min3 a b c = minNat a (minNat b c)
clamp n low high = maxNat low (minNat high n)
pow2 n = case n of { Zero -> Succ Zero; Succ m -> double (pow2 m) }
isPow2 n = case n of { Zero -> False; Succ m -> case m of { Zero -> True; Succ n' -> andB (evenNat n) (isPow2 (half n)) } }
